spring:
  datasource:
    name: jk-fast-start
    url: jdbc:mysql://127.0.0.1:3306/jk_fast_start_db?useUnicode=true&characterEncoding=utf-8
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  freemarker:
    allow-request-override: true
    allow-session-override: true
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
shiro:
  realm-class: com.github.xuejike.springboot.jkfaststart.shiro.UserRealm
  login-url: /admin/public/login
  success-url: /admin/index
  sign-in:
    user-param: username
    password-param: pwd
  hash-iterations: 1 #加密迭代次数，强制设为至少1次（即使设置0或负数）
  hash-algorithm-name: MD5 #加密算法名称，如：MD2/SHA-1/SHA-256/SHA-384/SHA-512
  filters:
      myfilter: com.github.xuejike.springboot.jkfaststart.shiro.MyFilter
  filter-chain-definitions: #默认为空，一般如下配置
      /admin/public/logout: logout
      /admin/**: authc,myfilter
      /**: anon
  retry-max: 100
